# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T02:30:22+00:00

from __future__ import annotations

from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, Field


class Empty(BaseModel):
    pass


class PlaceActionType(Enum):
    PLACE_ACTION_TYPE_UNSPECIFIED = 'PLACE_ACTION_TYPE_UNSPECIFIED'
    APPOINTMENT = 'APPOINTMENT'
    ONLINE_APPOINTMENT = 'ONLINE_APPOINTMENT'
    DINING_RESERVATION = 'DINING_RESERVATION'
    FOOD_ORDERING = 'FOOD_ORDERING'
    FOOD_DELIVERY = 'FOOD_DELIVERY'
    FOOD_TAKEOUT = 'FOOD_TAKEOUT'
    SHOP_ONLINE = 'SHOP_ONLINE'


class ProviderType(Enum):
    PROVIDER_TYPE_UNSPECIFIED = 'PROVIDER_TYPE_UNSPECIFIED'
    MERCHANT = 'MERCHANT'
    AGGREGATOR_3P = 'AGGREGATOR_3P'


class PlaceActionLink(BaseModel):
    createTime: Optional[str] = Field(
        None,
        description='Output only. The time when the place action link was created.',
    )
    isEditable: Optional[bool] = Field(
        None,
        description='Output only. Indicates whether this link can be edited by the client.',
    )
    isPreferred: Optional[bool] = Field(
        None,
        description='Optional. Whether this link is preferred by the merchant. Only one link can be marked as preferred per place action type at a location. If a future request marks a different link as preferred for the same place action type, then the current preferred link (if any exists) will lose its preference.',
    )
    name: Optional[str] = Field(
        None,
        description='Optional. The resource name, in the format `locations/{location_id}/placeActionLinks/{place_action_link_id}`. The name field will only be considered in UpdatePlaceActionLink and DeletePlaceActionLink requests for updating and deleting links respectively. However, it will be ignored in CreatePlaceActionLink request, where `place_action_link_id` will be assigned by the server on successful creation of a new link and returned as part of the response.',
    )
    placeActionType: Optional[PlaceActionType] = Field(
        None,
        description='Required. The type of place action that can be performed using this link.',
    )
    providerType: Optional[ProviderType] = Field(
        None, description='Output only. Specifies the provider type.'
    )
    updateTime: Optional[str] = Field(
        None,
        description='Output only. The time when the place action link was last modified.',
    )
    uri: Optional[str] = Field(
        None,
        description='Required. The link uri. The same uri can be reused for different action types across different locations. However, only one place action link is allowed for each unique combination of (uri, place action type, location).',
    )


class PlaceActionTypeMetadata(BaseModel):
    displayName: Optional[str] = Field(
        None,
        description='The localized display name for the attribute, if available; otherwise, the English display name.',
    )
    placeActionType: Optional[PlaceActionType] = Field(
        None, description='The place action type.'
    )


class FieldXgafv(Enum):
    field_1 = '1'
    field_2 = '2'


class Alt(Enum):
    json = 'json'
    media = 'media'
    proto = 'proto'


class ListPlaceActionLinksResponse(BaseModel):
    nextPageToken: Optional[str] = Field(
        None,
        description='If there are more place action links than the requested page size, then this field is populated with a token to fetch the next page of results.',
    )
    placeActionLinks: Optional[List[PlaceActionLink]] = Field(
        None, description='The returned list of place action links.'
    )


class ListPlaceActionTypeMetadataResponse(BaseModel):
    nextPageToken: Optional[str] = Field(
        None,
        description='If the number of action types exceeded the requested page size, this field will be populated with a token to fetch the next page on a subsequent call to `placeActionTypeMetadata.list`. If there are no more results, this field will not be present in the response.',
    )
    placeActionTypeMetadata: Optional[List[PlaceActionTypeMetadata]] = Field(
        None,
        description='A collection of metadata for the available place action types.',
    )
